### ISSUE TITLE
NASDF conflicts (Guix in particular)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/ntemplate#10]
When packaging NASDF-enabled packages in Guix, we run into a priority conflict over which NASDF to use which leads to Guix packaging errors.

For instance, when packaging Nfiles which depends on Nclasses, Guix first sees NASDF in Nfiles, thus retriggers the rebuild of Nclasses, which is read-only at this point, which results in a build error.

The quick and dirty work around is to add this phase:

```scm
(add-after 'unpack 'remove-nasdf-duplicate
          (lambda* (#:key inputs #:allow-other-keys)
            (delete-file-recursively "nasdf")))
```

Can we do better?
@aartaka ?

**Comment by Ambrevar** [comment]
Suggestion: Create an `sbcl-nasdf` Guix package, and package all NASDF-enabled packages without the NASDF folder, but with the `sbcl-nasdf` native-input instead.

**Comment by Ambrevar** [comment]
Applied to Guix master (08edbd2535ae622d319a51e6f877d23d75dc24f3).  Feel free to reopen if you think this is not the right strategy.

**Comment by aartaka** [comment]
Feels like a right move `o((*^▽^*))o`
