### ISSUE TITLE
Release 0.1.6 ?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/ntemplate#14]
There are some important new commits on master on which Nyxt install depends.

I propose to release a new version then we can update https://github.com/atlas-engineer/nyxt/pull/2925#issuecomment-1545805076.

But maybe we want to include https://github.com/atlas-engineer/nyxt/pull/2963 in this release?

@aartaka ?

**Comment by aartaka** [comment]
Sure thing!

**Comment by aartaka** [comment]
Oh, sorry for the meaningless comment :D 

I mean: let's have the changes integrated now, and then maybe integrate the install action into the next release.

**Comment by aadcg** [comment]
I've noticed that this repository doesn't tag releases (versions are simply bumped). Is that done for a specific reason?

**Comment by Ambrevar** [comment]
> d then maybe integrate the install action into the next release.

Actually I'm almost done with the install action, only 1 bug fix remaining.

**Comment by aartaka** [comment]
> I've noticed that this repository doesn't tag releases (versions are simply bumped). Is that done for a specific reason?

Yes. `ntemplate` is not the same as NASDF, so changing the `ntemplate` version to the one of NASDF is not really semantically true. 

But there's no hurt (at the moment, at least) in doing it, I guess.

**Comment by Ambrevar** [comment]
I've released 0.1.6 (without https://github.com/atlas-engineer/nyxt/pull/2963 because I don't want to delay further).

I've updated the Nyxt NASDF update, see https://github.com/atlas-engineer/nyxt/pull/3003.
